import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from scipy import stats
from pathlib import Path
import sys
import yaml
import pickle
from datetime import datetime

# First, train a model from training data with "python linear_regression.py <training_data.csv>"
#   this is in generated by automate.py to ml-agents/config/multi/{GamePPO.#.initials}/{GamePPO.#.initials.csv} 
#   ((for me, inside e.g. BasicPPO.4.AK/BasicPPO.4.AK.csv))

# Then, predict the RAM for a config with "python linear_regression.py --predict <config.yaml> [model.pkl]"

def analyze_ram_usage(csv_path, output_dir=None, use_percentage=False):
    # Load data
    df = pd.read_csv(csv_path)
    
    # Set up output directory and log file
    if output_dir is None:
        output_dir = Path(csv_path).parent / "ram_analysis"
    else:
        output_dir = Path(output_dir)
    
    output_dir.mkdir(exist_ok=True, parents=True)
    
    # Create log file
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_file = output_dir / f"analysis_log_{timestamp}.txt"
    
    def log_and_print(message):
        """Print to terminal and write to log file"""
        print(message)
        with open(log_file, 'a', encoding='utf-8') as f:
            f.write(message + '\n')
    
    log_and_print(f"Linear Regression Analysis Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    log_and_print(f"Input CSV: {csv_path}")
    log_and_print(f"Output Directory: {output_dir}")
    log_and_print(f"Loaded {len(df)} training runs\n")
    
    # Get hyperparameter columns (hardware specs and RAM metrics both)
    hw_cols = ["ID", "cpu_type", "cpu_freqcpu_cores", "ram_gb", "has_nvidia", 
               "nvidia_gpu_name", "nvidia_vram_gb", "os"]
    result_cols = ["ram_mb_used", "ram_usage_percent", "ram_avg_percent",
                   "benchmark_steps", "benchmark_mean", "benchmark_reached"]
    
    hp_cols = [col for col in df.columns if col not in hw_cols and col not in result_cols]
    log_and_print(f"Hyperparameters found: {hp_cols}\n")
    
    # Extract hardware features for controlling for different machines
    hw_features = ["ram_gb", "has_nvidia"]
    hw_available = [col for col in hw_features if col in df.columns]
    
    # Prep data. Get numeric hyperparameters AND hardware features
    X_hp = df[hp_cols].select_dtypes(include=[np.number])
    X_hp = X_hp.loc[:, X_hp.nunique() > 1]
    
    # Add hardware features
    X_hw = df[hw_available].select_dtypes(include=[np.number])
    X_hw = X_hw.loc[:, X_hw.nunique() > 1]
    
    # Combine hyperparameters and hardware into one feature set
    X = pd.concat([X_hp, X_hw], axis=1)
    
    # Choose target variable
    if use_percentage:
        if "ram_usage_percent" not in df.columns:
            log_and_print("Error: ram_usage_percent column not found in data")
            return
        y = df["ram_usage_percent"]
        target_name = "RAM Usage %"
        target_unit = "%"
    else:
        y = df["ram_mb_used"]
        target_name = "RAM Usage"
        target_unit = "MB"
    
    # Remove NaN rows
    mask = ~(X.isna().any(axis=1) | y.isna())
    X, y = X[mask], y[mask]
    
    if X.shape[1] == 0:
        log_and_print("No varying hyperparameters found")
        return
    
    log_and_print(f"Analyzing hyperparameters: {list(X_hp.columns)}")
    log_and_print(f"Controlling for hardware: {list(X_hw.columns)}")
    log_and_print(f"Samples: {len(X)}\n")
    
    # Standardize features using scikit StandardScaler -> calculates mean and standard deviation of each hyperparam in training data
    scaler = StandardScaler()
    X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)
    
    # Fit linear regression
    model = LinearRegression()
    model.fit(X_scaled, y)
    y_pred = model.predict(X_scaled)
    r2 = model.score(X_scaled, y)
    
    # Calculate p-values
    n, k = len(y), X_scaled.shape[1]
    residuals = y - y_pred
    mse = np.sum(residuals**2) / (n - k - 1)
    
    try:
        var_coef = mse * np.linalg.inv(X_scaled.T @ X_scaled).diagonal()
        std_errors = np.sqrt(var_coef)
        t_stats = model.coef_ / std_errors
        p_values = 2 * (1 - stats.t.cdf(np.abs(t_stats), n - k - 1))
    except np.linalg.LinAlgError: #throw error
        log_and_print("Warning: could not compute p-values\n")
        std_errors = [np.nan] * k
        p_values = [np.nan] * k
    
    # Create results - separate hyperparameters from hardware controls
    hp_indices = [i for i, col in enumerate(X.columns) if col in X_hp.columns]
    hw_indices = [i for i, col in enumerate(X.columns) if col in X_hw.columns]
    
    results_hp = pd.DataFrame({
        'Hyperparameter': [X.columns[i] for i in hp_indices],
        'Coefficient': [model.coef_[i] for i in hp_indices],
        'P_Value': [p_values[i] for i in hp_indices],
        'Significant': [p_values[i] < 0.05 if not pd.isna(p_values[i]) else False for i in hp_indices]
    }).sort_values('Coefficient', key=abs, ascending=False)
    
    results_hw = pd.DataFrame({
        'Hardware': [X.columns[i] for i in hw_indices],
        'Coefficient': [model.coef_[i] for i in hw_indices],
        'P_Value': [p_values[i] for i in hw_indices],
        'Significant': [p_values[i] < 0.05 if not pd.isna(p_values[i]) else False for i in hw_indices]
    }).sort_values('Coefficient', key=abs, ascending=False)
    
    # Print summary
    log_and_print(f"Linreg analysis of {target_name} Prediction")
    
    # Prediction accuracy
    log_and_print(f"\nPrediction accuracy:")
    log_and_print(f"  R-squared: {r2:.4f}")
    log_and_print(f"  So, the model explains {r2*100:.1f}% of variance in {target_name}")
    
    # Check R2 to determine how strong the predictive power of the model (so with the varying hyperparams' impact on RAM usage)
    if r2 >= 0.7:
        log_and_print(f"Model has strong predictive power")
    elif r2 >= 0.4:
        log_and_print(f"Model has moderate predictive power")
    else:
        log_and_print(f"Model has weak predictive power -> other factors likely matter more")
    
    # Prediction formula
    log_and_print(f"\nPrediction is based on this calculation:")
    intercept = y.mean() - sum(model.coef_[i] * X[col].mean() / X[col].std() 
                                for i, col in enumerate(X.columns))
    formula_parts = [f"{intercept:.2f}"]
    
    for i, col in enumerate(X.columns):
        coef_unscaled = model.coef_[i] / scaler.scale_[i]
        sign = "+" if coef_unscaled >= 0 else ""
        formula_parts.append(f"{sign}{coef_unscaled:.2f}*{col}")
    
    # Print out the formula of the prediction
    log_and_print(f"  {target_name} ({target_unit}) = {' '.join(formula_parts)}")
    
    # Coefficient table - shows both hyperparameters AND hardware
    log_and_print(f"\nHyperparameter effects (controlling for hardware):")
    log_and_print(f"{'Hyperparameter':<20} {'Coefficient':>12} {'P-Value':>12} {'Sig':>5}")
    log_and_print("-"*70)
    
    for _, row in results_hp.iterrows():
        p_str = f"{row['P_Value']:.4f}" if not pd.isna(row['P_Value']) else "N/A"
        sig = "***" if row['P_Value'] < 0.001 else "**" if row['P_Value'] < 0.01 else "*" if row['P_Value'] < 0.05 else ""
        log_and_print(f"{row['Hyperparameter']:<20} {row['Coefficient']:>12.2f} {p_str:>12} {sig:>5}")
    
    log_and_print("\n\nHardware control variables:")
    log_and_print(f"{'Hardware':<20} {'Coefficient':>12} {'P-Value':>12} {'Sig':>5}")
    log_and_print("-"*70)
    
    for _, row in results_hw.iterrows():
        p_str = f"{row['P_Value']:.4f}" if not pd.isna(row['P_Value']) else "N/A"
        sig = "***" if row['P_Value'] < 0.001 else "**" if row['P_Value'] < 0.01 else "*" if row['P_Value'] < 0.05 else ""
        log_and_print(f"{row['Hardware']:<20} {row['Coefficient']:>12.2f} {p_str:>12} {sig:>5}")
    
    log_and_print("\nSignificance: *** p<0.001, ** p<0.01, * p<0.05")
    
    # Summarize the significancy - updated to use results_hp
    significant = results_hp[results_hp['Significant']]
    if len(significant) > 0:
        log_and_print(f"\nSignificant hyperparameters (p < 0.05), after controlling for hardware:")
        for _, row in significant.iterrows():
            effect = "Increases" if row['Coefficient'] > 0 else "Decreases"
            log_and_print(f"  {row['Hyperparameter']}: {effect} RAM usage")
            log_and_print(f"  Coefficient: {row['Coefficient']:.2f} MB per unit")
    else:
        log_and_print("\nNo significant hyperparameter effects found (p >= 0.05)")
        log_and_print("  -> Hyperparameters don't significantly affect RAM usage (after accounting for hardware)")
    
    # Answer RAM research Q based on R2
    log_and_print(f"Can we predict the average amount of RAM used during agent training?")
    
    if r2 >= 0.5 and len(significant) > 0:
        log_and_print(f"  -> Yes, with {r2*100:.1f}% accuracy, based on: {', '.join(significant['Hyperparameter'].tolist())}")
    elif r2 >= 0.3:
        log_and_print(f"  -> Partially. We can predict {r2*100:.1f}% of RAM variance, so other factors not measured can also affect RAM  usage")
    else:
        log_and_print(f"  -> No, because the model only explains {r2*100:.1f}% of variance, so these tested hyperparameters can't predict well the RAM usage")
    
    # Save results
    results_hp.to_csv(output_dir / "regression_results_hyperparameters.csv", index=False)
    results_hw.to_csv(output_dir / "regression_results_hardware.csv", index=False)
    log_and_print(f"\nHyperparameter results saved to: {output_dir / 'regression_results_hyperparameters.csv'}")
    log_and_print(f"Hardware results saved to: {output_dir / 'regression_results_hardware.csv'}")
    
    # Plot 1: Actual vs Predicted
    plt.figure(figsize=(8, 7))
    plt.scatter(y, y_pred, alpha=0.6, s=100, edgecolors='black', linewidth=0.5)
    min_val = min(y.min(), y_pred.min())
    max_val = max(y.max(), y_pred.max())
    plt.plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=2, 
             label='Perfect Prediction', alpha=0.7)
    mae = np.mean(np.abs(y - y_pred))
    
    plt.xlabel(f'Actual {target_name} ({target_unit})', fontsize=12)
    plt.ylabel(f'Predicted {target_name} ({target_unit})', fontsize=12)
    plt.title(f'{target_name} Prediction Accuracy\nR² = {r2:.3f}, Mean Error = {mae:.1f} {target_unit}', 
              fontsize=13, fontweight='bold')
    plt.legend(fontsize=11)
    plt.grid(alpha=0.3, linestyle='--')
    plt.tight_layout()
    
    # Save plot
    plot1_path = output_dir / "prediction_accuracy.png"
    plt.savefig(plot1_path, dpi=300, bbox_inches='tight')
    log_and_print(f"Prediction accuracy plot saved to: {plot1_path}")
    plt.show()
    
    
    # Plot 2: Residual Plot
    plt.figure(figsize=(8, 6))
    residuals = y - y_pred
    plt.scatter(y_pred, residuals, alpha=0.6, s=80, edgecolors='black', linewidth=0.5)
    plt.axhline(y=0, color='r', linestyle='--', linewidth=2, alpha=0.7)
    
    plt.xlabel(f'Predicted {target_name} ({target_unit})', fontsize=12)
    plt.ylabel(f'Residual (Actual - Predicted, {target_unit})', fontsize=12)
    plt.title('Residual Plot - Prediction Errors', fontsize=13, fontweight='bold')
    plt.grid(alpha=0.3, linestyle='--')
    plt.tight_layout()
    
    # Save plot
    plot2_path = output_dir / "residual_plot.png"
    plt.savefig(plot2_path, dpi=300, bbox_inches='tight')
    log_and_print(f"Residual plot saved to: {plot2_path}")
    plt.show()
    
    # Save trained model
    model_data = {
        'model': model,
        'scaler': scaler,
        'feature_columns': list(X.columns),
        'target_mean': y.mean(),
        'r2_score': r2,
        'target_type': 'percentage' if use_percentage else 'absolute'
    }
    
    model_path = output_dir / "trained_model.pkl"
    with open(model_path, 'wb') as f:
        pickle.dump(model_data, f)
    log_and_print(f"Trained model saved to: {model_path}")
    log_and_print(f"Analysis log saved to: {log_file}")
    
    return model_data


# This is for the Ram prediction based on a specific YAML config file
def predict_ram_for_config(config_path, model_path=None, ram_gb=None, has_nvidia=None):
    # config_path is the path to YAML config file
    # model_path is optional, but it's the path to trained model pickle file
    # ram_gb and has_nvidia are optional hardware specs for prediction
    
    config_path = Path(config_path)
    
    # Load config
    if not config_path.exists():
        print(f"Error: config file not found: {config_path}")
        return None
    
    try:
        with open(config_path, 'r') as f:
            config = yaml.safe_load(f)
        print(f"Loaded config: {config_path}")
    except Exception as e:
        print(f"Error loading YAML config: {e}")
        return None
    
    # When model file was not provided (bc it's optional), look for the model file
    if model_path is None:
        # Search for model file in same directory as script
        script_dir = Path(__file__).parent
        model_path = script_dir / "ram_analysis" / "trained_model.pkl"
        
        if not model_path.exists():
            print(f"Error: no trained model found at {model_path}")
            print("Run the analysis first to train a model.")
            return None
    
    # Load trained model
    try:
        with open(model_path, 'rb') as f:
            model_data = pickle.load(f)
        print(f"Loaded trained model from: {model_path}")
        print(f"Model R² score: {model_data['r2_score']:.4f}")
    except Exception as e:
        print(f"Error loading model: {e}")
        return None
    
    model = model_data['model']
    scaler = model_data['scaler']
    feature_columns = model_data['feature_columns']
    
    # Convert the nested (indented) YAML file into a flat dictionary (each line its own path) - so, flattening the config to get hyperparams
    def flatten_dict(d, parent_key='', sep='_'):
        items = []
        for k, v in d.items():
            new_key = f"{parent_key}{sep}{k}" if parent_key else k
            if isinstance(v, dict):
                items.extend(flatten_dict(v, new_key, sep=sep).items())
            else:
                items.append((new_key, v))
        return dict(items)
    
    flat_config = flatten_dict(config)
    print(f"\nFlattened config parameters:")
    for k, v in flat_config.items():
        print(f"  {k}: {v}")
    
    # Create feature vector for prediction (ordered list of numerical values of the input vars (so, hyperparams))
    config_features = {}
    missing_features = []
    
    for feature in feature_columns:
        # Check if it's a hardware feature that was provided as argument
        if feature == 'ram_gb' and ram_gb is not None:
            config_features[feature] = ram_gb
            continue
        elif feature == 'has_nvidia' and has_nvidia is not None:
            config_features[feature] = 1 if has_nvidia else 0
            continue
        
        found = False
        for flat_key, flat_value in flat_config.items():
            if flat_key.endswith(f"_{feature}") or flat_key == feature:
                try:
                    value = float(flat_value)
                    config_features[feature] = value
                    found = True
                    break
                except (ValueError, TypeError):
                    pass
        
        if not found:
            missing_features.append(feature)
    
    if missing_features:
        print(f"\nWarning: there are missing features in config: {missing_features}")
        if 'ram_gb' in missing_features or 'has_nvidia' in missing_features:
            print("Tip: Provide hardware specs with: --ram-gb <value> --has-nvidia <true/false>")
        print("These will be set to 0 , which may affect the accuracy of the prediction.")
        
    # Build the feature vector with same order of values as in the training model
    X_config = []
    for feature in feature_columns:
        if feature in config_features:
            X_config.append(config_features[feature])
        else:
            X_config.append(0)  # set to 0 for missing features (this is what the warning was about)
    
    # Convert to DataFrame to preserve feature names (avoids sklearn warnings)
    X_config_df = pd.DataFrame([X_config], columns=feature_columns)
    
    # Standardize features using trained scaler (trained in analyze_ram_usage function)
    X_config_scaled = scaler.transform(X_config_df)
    
    # Make the prediction
    predicted_ram = model.predict(X_config_scaled)[0]
    
    #print results
    print(f"RAM usage prediction")
    print(f"  Config file used: {config_path.name}")
    print(f"  Predicted RAM usage: {predicted_ram:.0f} MB ({predicted_ram/1024:.2f} GB)")
    print(f"  Model confidence (R²): {model_data['r2_score']:.4f}")
    
    #Output if prediction is  accurate or not
    if model_data['r2_score'] < 0.5:
        print(f"\n   Warning: Model has low accuracy (R² < 0.5). Prediction may be unreliable")
    elif len(missing_features) > len(feature_columns) / 2:
        print(f"\n   Warning: Many features missing from config, so prediction may not be accurate")
    
    # Based on coefficients in linreg formula, print which features contributed most to the prediction
    print(f"\nFeature contributions:")
    feature_contributions = X_config_scaled[0] * model.coef_
    contribution_data = list(zip(feature_columns, X_config_df.values[0], feature_contributions))
    contribution_data.sort(key=lambda x: abs(x[2]), reverse=True)
    
    for feature, value, contrib in contribution_data[:5]:  # list top 5 contributors
        print(f"  {feature}: {value} → {contrib:+.1f} MB")

    output_dir = Path(config_path).parent / "ram_predictions"
    output_dir.mkdir(exist_ok=True)
    
    prediction_file = output_dir / f"{config_path.stem}_prediction.txt"
    with open(prediction_file, 'w', encoding='utf-8') as f:
        f.write(f"Config: {config_path.name}\n")
        f.write(f"Predicted RAM: {predicted_ram:.0f} MB ({predicted_ram/1024:.2f} GB)\n")
        f.write(f"Model R²: {model_data['r2_score']:.4f}\n")
        f.write(f"\nTop feature contributions:\n")
        for feature, value, contrib in contribution_data[:5]:
            f.write(f"  {feature}: {value} → {contrib:+.1f} MB\n")
    
    print(f"\nPrediction saved to: {prediction_file}")
    
    return predicted_ram


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage:")
        print("  Train model: python linear_regression.py <path_to_csv> [--percentage]")
        print("  Predict RAM: python linear_regression.py --predict <config.yaml> [model.pkl] [--ram-gb X] [--has-nvidia true/false]")
        sys.exit(1)
    
    if sys.argv[1] == "--predict":
        if len(sys.argv) < 3:
            print("Error: Please provide config file path")
            print("Usage: python linear_regression.py --predict <config.yaml> [model.pkl] [--ram-gb X] [--has-nvidia true/false]")
            sys.exit(1)
        
        config_path = sys.argv[2]
        model_path = None
        ram_gb = None
        has_nvidia = None
        
        # Parse additional arguments
        i = 3
        while i < len(sys.argv):
            if sys.argv[i] == '--ram-gb' and i + 1 < len(sys.argv):
                ram_gb = float(sys.argv[i + 1])
                i += 2
            elif sys.argv[i] == '--has-nvidia' and i + 1 < len(sys.argv):
                has_nvidia = sys.argv[i + 1].lower() in ['true', '1', 'yes']
                i += 2
            elif not sys.argv[i].startswith('--'):
                model_path = sys.argv[i]
                i += 1
            else:
                i += 1
        
        predict_ram_for_config(config_path, model_path, ram_gb, has_nvidia)
    else:
        # Original analysis mode
        csv_path = Path(sys.argv[1])
        if not csv_path.exists():
            print(f"Error: File not found: {csv_path}")
            sys.exit(1)
        
        analyze_ram_usage(csv_path)