import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from scipy import stats
from pathlib import Path
import sys
import yaml
import pickle

# First, train a model from training data with "python linear_regression.py <training_data.csv>"
#   this is in generated by automate.py to ml-agents/config/multi/{GamePPO.#.initials}/{GamePPO.#.initials.csv} 
#   ((for me, inside e.g. BasicPPO.4.AK/BasicPPO.4.AK.csv))

# Then, predict the RAM for a config with "python linear_regression.py --predict <config.yaml> [model.pkl]"

def analyze_ram_usage(csv_path):
   
    # Load data
    df = pd.read_csv(csv_path)
    print(f"Loaded {len(df)} training runs\n")
    
    # Get hyperparameter columns (hardware specs and RAM metrics both)
    hw_cols = ["ID", "cpu_type", "cpu_freqcpu_cores", "ram_gb", "has_nvidia", 
               "nvidia_gpu_name", "nvidia_vram_gb", "os"]
    result_cols = ["ram_mb_used", "ram_usage_percent", "ram_avg_percent",
                   "benchmark_steps", "benchmark_mean", "benchmark_reached"]
    
    hp_cols = [col for col in df.columns if col not in hw_cols and col not in result_cols]
    print(f"Hyperparameters found: {hp_cols}\n")
    
    # Prep data. Get only numeric hyperparameters
    X = df[hp_cols].select_dtypes(include=[np.number])
    X = X.loc[:, X.nunique() > 1]  # Remove constant columns (bc we only want to see the impact of the varying hyperparams)
    y = df["ram_mb_used"]
    
    # Remove NaN rows
    mask = ~(X.isna().any(axis=1) | y.isna())
    X, y = X[mask], y[mask]
    
    if X.shape[1] == 0:
        print("No varying hyperparameters found")
        return
    
    print(f"Analyzing: {list(X.columns)}")
    print(f"Samples: {len(X)}\n")
    
    # Standardize features using scikit StandardScaler -> calculates mean and standard deviation of each hyperparam in training data
    scaler = StandardScaler()
    X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)
    
    # Fit linear regression
    model = LinearRegression()
    model.fit(X_scaled, y)
    y_pred = model.predict(X_scaled)
    r2 = model.score(X_scaled, y)
    
    # Calculate p-values
    n, k = len(y), X_scaled.shape[1]
    residuals = y - y_pred
    mse = np.sum(residuals**2) / (n - k - 1)
    
    try:
        var_coef = mse * np.linalg.inv(X_scaled.T @ X_scaled).diagonal()
        std_errors = np.sqrt(var_coef)
        t_stats = model.coef_ / std_errors
        p_values = 2 * (1 - stats.t.cdf(np.abs(t_stats), n - k - 1))
    except np.linalg.LinAlgError: #throw error
        print("Warning: could not compute p-values\n")
        std_errors = [np.nan] * k
        p_values = [np.nan] * k
    
    # Create results
    results = pd.DataFrame({
        'Hyperparameter': X.columns,
        'Coefficient': model.coef_,
        'P_Value': p_values,
        'Significant': [p < 0.05 if not pd.isna(p) else False for p in p_values]
    }).sort_values('Coefficient', key=abs, ascending=False)
    
    # Print summary
    print(f"Linreg analysis of RAM Usage Prediction")
    
    # Prediction accuracy
    print(f"\nPrediction accuracy:")
    print(f"  R-squared: {r2:.4f}")
    print(f"  So, the model explains {r2*100:.1f}% of variance in RAM usage")
    
    # Check R2 to determine how strong the predictive power of the model (so with the varying hyperparams' impact on RAM usage)
    if r2 >= 0.7:
        print(f"Model has strong predictive power")
    elif r2 >= 0.4:
        print(f"Model has moderate predictive power")
    else:
        print(f"Model has weak predictive power -> other factors likely matter more")
    
    # Prediction formula
    print(f"\nPrediction is based on this calculation:")
    intercept = y.mean() - sum(model.coef_[i] * X[col].mean() / X[col].std() 
                                for i, col in enumerate(X.columns))
    formula_parts = [f"{intercept:.2f}"]
    
    for i, col in enumerate(X.columns):
        coef_unscaled = model.coef_[i] / scaler.scale_[i]
        sign = "+" if coef_unscaled >= 0 else ""
        formula_parts.append(f"{sign}{coef_unscaled:.2f}*{col}")
    
    # Print out the forumala of the prediciton
    print(f"  RAM (MB) = {' '.join(formula_parts)}")
    
    # Coefficient table (to check which are significant or not)
    print(f"\nHyperparam effects:")
    print(f"{'Hyperparameter':<20} {'Coefficient':>12} {'P-Value':>12} {'Sig':>5}")
    print("-"*70)
    
    for _, row in results.iterrows():
        p_str = f"{row['P_Value']:.4f}" if not pd.isna(row['P_Value']) else "N/A"
        sig = "***" if row['P_Value'] < 0.001 else "**" if row['P_Value'] < 0.01 else "*" if row['P_Value'] < 0.05 else ""
        print(f"{row['Hyperparameter']:<20} {row['Coefficient']:>12.2f} {p_str:>12} {sig:>5}")
    
    print("\nSignificance: *** p<0.001, ** p<0.01, * p<0.05")
    
    # Summarize the significancy of the variables
    significant = results[results['Significant']]
    if len(significant) > 0:
        print(f"\nSignificant variables (p < 0.05):")
        for _, row in significant.iterrows():
            effect = "Increases" if row['Coefficient'] > 0 else "Decreases"
            print(f"  {row['Hyperparameter']}: {effect} RAM usage")
            print(f"  Coefficient: {row['Coefficient']:.2f} MB per unit")
    else:
        print("\nNo significant effects found (p >= 0.05)")
        print("  -> Neither of the varying hyperparameters affects RAM usage significantly")
    
    # Answer RAM research Q based on R2
    print(f"Can we predict the average amount of RAM used during agent training?")
    
    if r2 >= 0.5 and len(significant) > 0:
        print(f"  -> Yes, with {r2*100:.1f}% accuracy, based on: {', '.join(significant['Hyperparameter'].tolist())}")
    elif r2 >= 0.3:
        print(f"  -> Partially. We can predict {r2*100:.1f}% of RAM variance, so other factors not measured can also affect RAM  usage")
    else:
        print(f"  -> No, because the model only explains {r2*100:.1f}% of variance, so these tested hyperparameters can't predict well the RAM usage")
    
    # Save results
    output_dir = Path(csv_path).parent / "ram_analysis"
    output_dir.mkdir(exist_ok=True)
    results.to_csv(output_dir / "regression_results.csv", index=False)
    print(f"\nResults were saved to: {output_dir / 'regression_results.csv'}")
    
    # Plot 1: Actual vs Predicted (RAM usage) - using a scatter plot
    # the points close to the red diagonal line = accurate predictions
    # obviously, the more scatter, the less accurate the prediction
    
    plt.figure(figsize=(8, 7))
    plt.scatter(y, y_pred, alpha=0.6, s=100, edgecolors='black', linewidth=0.5)
    min_val = min(y.min(), y_pred.min())
    max_val = max(y.max(), y_pred.max())
    plt.plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=2, 
             label='Perfect Prediction', alpha=0.7)
    mae = np.mean(np.abs(y - y_pred)) #calculate, display mean abs error
    
    plt.xlabel('Actual RAM Usage (MB)', fontsize=12)
    plt.ylabel('Predicted RAM Usage (MB)', fontsize=12)
    plt.title(f'RAM Usage Prediction Accuracy\nR² = {r2:.3f}, Mean Error = {mae:.0f} MB', 
              fontsize=13, fontweight='bold')
    plt.legend(fontsize=11)
    plt.grid(alpha=0.3, linestyle='--')
    plt.tight_layout()
    
    # Save plot
    plot1_path = output_dir / "prediction_accuracy.png"
    plt.savefig(plot1_path, dpi=300, bbox_inches='tight')
    print(f"Prediction accuracy plot saved to: {plot1_path}")
    plt.show()
    
    
    # Plot 2: Residual Plot (that shows prediction errors)
    # residuals = actual - predicted
    # if the points are scattered randomly around zero, it's a good model (-> no systematic bias).
    # if there are patterns, the model's missing sth
    
    plt.figure(figsize=(8, 6))
    residuals = y - y_pred
    plt.scatter(y_pred, residuals, alpha=0.6, s=80, edgecolors='black', linewidth=0.5)
    plt.axhline(y=0, color='r', linestyle='--', linewidth=2, alpha=0.7) #reference line
    
    plt.xlabel('Predicted RAM Usage (MB)', fontsize=12)
    plt.ylabel('Residual (Actual - Predicted, MB)', fontsize=12)
    plt.title('Residual Plot - Prediction Errors', fontsize=13, fontweight='bold')
    plt.grid(alpha=0.3, linestyle='--')
    plt.tight_layout()
    
    # Save plot
    plot2_path = output_dir / "residual_plot.png"
    plt.savefig(plot2_path, dpi=300, bbox_inches='tight')
    print(f"Residual plot saved to: {plot2_path}")
    plt.show()
    
    # Save trained model for prediction
    model_data = {
        'model': model,
        'scaler': scaler,
        'feature_columns': list(X.columns),
        'target_mean': y.mean(),
        'r2_score': r2
    }
    
    model_path = output_dir / "trained_model.pkl"
    with open(model_path, 'wb') as f:
        pickle.dump(model_data, f)
    print(f"Trained model saved to: {model_path}")
    
    return model_data


# This is for the Ram prediction based on a specific YAML config file
def predict_ram_for_config(config_path, model_path=None):
    # config_path is the path to YAML config file
    # model_path is optional, but it's the path to trained model pickle file
    # we use pickle file to store trained LR model, standardScaler, feature list, R2 score in a single file -> so we can load this single file and then use it for consistent predictions
    
    config_path = Path(config_path)
    
    # Load config
    if not config_path.exists():
        print(f"Error: config file not found: {config_path}")
        return None
    
    try:
        with open(config_path, 'r') as f:
            config = yaml.safe_load(f)
        print(f"Loaded config: {config_path}")
    except Exception as e:
        print(f"Error loading YAML config: {e}")
        return None
    
    # When model file was not provided (bc it's optional), look for the model file
    if model_path is None:
        # Search for model file in same directory as script
        script_dir = Path(__file__).parent
        model_path = script_dir / "ram_analysis" / "trained_model.pkl"
        
        if not model_path.exists():
            print(f"Error: no trained model found at {model_path}")
            print("Run the analysis first to train a model.")
            return None
    
    # Load trained model
    try:
        with open(model_path, 'rb') as f:
            model_data = pickle.load(f)
        print(f"Loaded trained model from: {model_path}")
        print(f"Model R² score: {model_data['r2_score']:.4f}")
    except Exception as e:
        print(f"Error loading model: {e}")
        return None
    
    model = model_data['model']
    scaler = model_data['scaler']
    feature_columns = model_data['feature_columns']
    
    # Convert the nested (indented) YAML file into a flat dictionary (each line its own path) - so, flattening the config to get hyperparams
    def flatten_dict(d, parent_key='', sep='_'):
        items = []
        for k, v in d.items():
            new_key = f"{parent_key}{sep}{k}" if parent_key else k
            if isinstance(v, dict):
                items.extend(flatten_dict(v, new_key, sep=sep).items())
            else:
                items.append((new_key, v))
        return dict(items)
    
    flat_config = flatten_dict(config)
    print(f"\nFlattened config parameters:")
    for k, v in flat_config.items():
        print(f"  {k}: {v}")
    
    # Create feature vector for prediction (ordered list of numerical values of the input vars (so, hyperparams))
    config_features = {}
    missing_features = []
    
    for feature in feature_columns:
        if feature in flat_config:
            try:
                # Convert to numeric values if possible
                value = float(flat_config[feature])
                config_features[feature] = value
            except (ValueError, TypeError):
                print(f"Warning: could not convert {feature}={flat_config[feature]} to a numeric value")
                missing_features.append(feature)
        else:
            missing_features.append(feature)
    
    if missing_features:
        print(f"\nWarning: there are missing features in config: {missing_features}")
        print("These will be set to 0 , which may affect the accuracy of the prediction.")
        
    # Build the feature vector with same order of values as in the training model
    X_config = []
    for feature in feature_columns:
        if feature in config_features:
            X_config.append(config_features[feature])
        else:
            X_config.append(0)  # set to 0 for missing features (this is what the warning was about)
    
    X_config = np.array(X_config).reshape(1, -1)
    
    # Standardize features using trained scaler (trained in analyze_ram_usage function)
    X_config_scaled = scaler.transform(X_config)
    
    # Make the prediction
    predicted_ram = model.predict(X_config_scaled)[0]
    
    #print results
    print(f"RAM usage prediction")
    print(f"  Config file used: {config_path.name}")
    print(f"  Predicted RAM usage: {predicted_ram:.0f} MB ({predicted_ram/1024:.2f} GB)")
    print(f"  Model confidence (R²): {model_data['r2_score']:.4f}")
    
    #Output if prediction is  accurate or not
    if model_data['r2_score'] < 0.5:
        print(f"\n   Warning: Model has low accuracy (R² < 0.5). Prediction may be unreliable")
    elif len(missing_features) > len(feature_columns) / 2:
        print(f"\n   Warning: Many features missing from config, so prediction may not be accurate")
    
    # Based on coefficients in linreg formula, print which features contributed most to the prediction
    print(f"\nFeature contributions:")
    feature_contributions = X_config_scaled[0] * model.coef_
    contribution_data = list(zip(feature_columns, X_config[0], feature_contributions))
    contribution_data.sort(key=lambda x: abs(x[2]), reverse=True)
    
    for feature, value, contrib in contribution_data[:5]:  # list top 5 contributors
        print(f"  {feature}: {value} → {contrib:+.1f} MB")
    
    return predicted_ram


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage:")
        print("  Train model: python linear_regression.py <path_to_csv>")
        print("  Predict RAM: python linear_regression.py --predict <config.yaml> [model.pkl]")
        sys.exit(1)
    
    if sys.argv[1] == "--predict":
        if len(sys.argv) < 3:
            print("Error: Please provide config file path")
            print("Usage: python linear_regression.py --predict <config.yaml> [model.pkl]")
            sys.exit(1)
        
        config_path = sys.argv[2]
        model_path = sys.argv[3] if len(sys.argv) > 3 else None
        predict_ram_for_config(config_path, model_path)
    else:
        # Original analysis mode
        csv_path = Path(sys.argv[1])
        if not csv_path.exists():
            print(f"Error: File not found: {csv_path}")
            sys.exit(1)
        
        analyze_ram_usage(csv_path)
